routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "FilmaiController@index");
Route::get('/about', "FilmaiController@about");
Route::get('/contact', "FilmaiController@contact");
Route::get('/movies', "FilmaiController@movies");

Auth::routes();

Route::resource('aktoriai', 'AktoriaiController');
Route::resource('rezisieriai', 'RezisieriaiController');
Route::resource('zanrai', 'ZanraiController');
Route::resource('paveiksleliai', 'PaveiksleliaiController');

Route::get('/home', 'HomeController@index')->name('home');
/*
|--------------------------------------------------------------------------
| These routes were added by jamesmills/laravel-admin page
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'roles'], 'roles' => 'admin'], function () {
    Route::get('/', 'Admin\AdminController@index')->name('dashboard');
    Route::resource('roles', '\JamesMills\LaravelAdmin\Controllers\Admin\RolesController');
    Route::resource('permissions', '\JamesMills\LaravelAdmin\Controllers\Admin\PermissionsController');
    Route::resource('users', '\JamesMills\LaravelAdmin\Controllers\Admin\UsersController');
});

resources/views/about.blade.php
@extends('layout.main')
 
@section('content')
<!-- Page Header -->
  <header class="masthead" style="background-image: url('img/about-bg1.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Apie svetaine</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Filmai.out – Lietuvos kino naujienų tinklalapis. Esame entuziastinga rašančių ir fotografuojančių žmonių komanda,
        rengianti interviu su Lietuvos kino kūrėjais, reportažus iš kino renginių ir premjerų. Puslapyje taip pat talpinama
        įvairi ir aktuali informacija apie kino filmus, kino industrijos įvykius ir renginius.</p>
      </div>
    </div>
  </div>

  <hr>
@endsection

resources/views/contact.blade.php
@extends('layout.main')
 
@section('content')
 <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/contact-bg1.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Susisiekite su mumis</h1>
            <span class="subheading">Turite klausimų, mes maloniai juos atsakysime</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Jeigu norite susisiekti užpildykite formą esančia apačioje</p>
        <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
        <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
        <!-- To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
        <form name="sentMessage" id="contactForm" novalidate>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Vardas</label>
              <input type="text" class="form-control" placeholder="Vardas" id="name" required data-validation-required-message="Įveskite savo vardą.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Email</label>
              <input type="email" class="form-control" placeholder="Email" id="email" required data-validation-required-message="Įveskite savo email adresą.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Tekstas</label>
              <textarea rows="5" class="form-control" placeholder="Tekstas" id="message" required data-validation-required-message="Įveskite tekstą."></textarea>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <br>
          <div id="success"></div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary" id="sendMessageButton">siūsti</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <hr>
@endsection

resources/views/home.blade.php
@extends('layout.main')
 
@section('content')
<!-- Page Header -->
  <header class="masthead" style="background-image: url('img/home-bg1.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Filmų aprašymai</h1>
            <span class="subheading">Skaitykite naujausių filmų aprašymus</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto-4">
        <div class="deze">
        <div class="post-preview">
          <a href="post.html">
            <img class="post-title" src="img/virselis1.jpg">
            <h2 class="post-title">
              Filmo pavadinimas
            </h2>
            <h3 class="post-subtitle">
              Filmo aprašymas
            </h3>
          </a>
          <p class="post-meta">Pildė:
            <a href="#">Vardas Pavardė</a>
            Vasario 12, 2019</p>
        </div>
        </div>
        <hr>
        <!-- Pager -->
        <div class="clearfix">
          <a class="btn btn-primary float-right" href="#">Senesni įrašai &rarr;</a>
        </div>
      </div>
    </div>
  </div>

  <hr>
@endsection

resources/views/login.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/movies.blade.php
@extends('layout.main')
 
@section('content')
 <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/post-bg1.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1>Visi filmų aprašymai</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <a href="http://spaceipsum.com/">Space Ipsum</a>. Photographs by
            <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>.</p>
        </div>
      </div>
    </div>
  </article>

  <hr>
@endsection

resources/views/navbar.blade.php
  <div id="app">
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="/filmai/public/">
                FILMAI.OUT
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->

                    <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/filmai/public/">Pagrindinis</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/filmai/public/movies">Filmų aprašymai</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/filmai/public/about">Apie</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/filmai/public/contact">Kontaktai</a>
          </li>
        </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>
                                
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('aktoriai.index') }}">Aktoriai</a>
                                    <a class="dropdown-item" href="{{ route('rezisieriai.index') }}">Režisieriai</a>
                                    <a class="dropdown-item" href="{{ route('zanrai.index') }}">Žanrai</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                                    
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            @csrf
                                        </form>
                                </div>
                            </li>
                            
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>