routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "FilmaiController@index");
Route::get('/about', "FilmaiController@about");
Route::get('/contact', "FilmaiController@contact");
Route::get('/movies', "FilmaiController@movies");

Auth::routes();

Route::resource('aktoriai', 'AktoriaiController');
Route::resource('rezisieriai', 'RezisieriaiController');
Route::resource('zanrai', 'ZanraiController');
Route::resource('paveiksleliai', 'PaveiksleliaiController');

Route::get('/home', 'HomeController@index')->name('home');
/*
|--------------------------------------------------------------------------
| These routes were added by jamesmills/laravel-admin page
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'roles'], 'roles' => 'admin'], function () {
    Route::get('/', 'Admin\AdminController@index')->name('dashboard');
    Route::resource('roles', '\JamesMills\LaravelAdmin\Controllers\Admin\RolesController');
    Route::resource('permissions', '\JamesMills\LaravelAdmin\Controllers\Admin\PermissionsController');
    Route::resource('users', '\JamesMills\LaravelAdmin\Controllers\Admin\UsersController');
});

app/zanrai.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class zanrai extends Model
{
    protected $fillable = [
        'id',
        'pavadinimas'
    ];
    protected $table = 'zanrai';
    public $primaryKey = 'id';
    public $timestamps = false;
}

app/Http/Controllers/ZanraiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\zanrai;

class ZanraiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $zanras = zanrai::orderBy('pavadinimas')->paginate(15);

        return view('zanrai.index')->with('zanrai', $zanras);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('zanrai.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Auth::check()) {
            // The user is logged in...
            $id = Auth::id();
            $request->validate([
                'pavadinimas'=>'required',
            ]);
            $zanras = new zanrai([
                'pavadinimas' => $request->get('pavadinimas')
            ]);
            $zanras->save();
            return redirect('/zanrai')->with('success', 'Žanras buvo sėkmingai sukurtas');
        } else {
            return redirect('/')->with('error', 'Būtina prisijungti');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $zanras = zanrai::find($id);
        return view('zanrai.show')->with('zanras', $zanras);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $zanras = zanrai::find($id);

        return view('zanrai.edit', compact('zanras'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (Auth::check()) {
            // The user is logged in...
            $request->validate([
                'pavadinimas'=>'required'
            ]);

            $id = $request->get('id');

            $zanras = zanrai::find($id);
            $zanras->pavadinimas = $request->get('pavadinimas');
            $zanras->save();

            return redirect('/zanrai')->with('success', 'Žanras buvo sėkmingai atnaujintas');
        } else {
            return redirect('/')->with('error', 'Būtina prisijungti');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $zanras = zanrai::find($id);
        $zanras->delete();

        return redirect('/zanrai')->with('success', 'Žanras sėkmingai pašalintas');
    }
}

resources/views/zanrai/create.blade.php
@extends('layout.main')
 
@section('content')
    <h1>Sukurti žanrą</h1>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    {!! Form::open(array('route' => 'zanrai.store')) !!}
        {!! Form::token() !!}
        <div class="form-group">
            {!! Form::label('pavadinimas', 'Pavadinimas') !!}
            {!! Form::text('pavadinimas', ' ', array('class' => 'form-control')) !!}
        </div>
        {!! Form::submit('Pridėti', array('class' => 'btn btn-primary')) !!} 
    {!! Form::close() !!}
@endsection

resources/views/zanrai/edit.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Redaguoti žanrą
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    {!! Form::open(array('route' => array('zanrai.update', $zanras->id))) !!}
        @method('PATCH')
        {!! Form::token() !!}
        {!! Form::hidden('id', $zanras->id) !!}
        <div class="form-group">
            {!! Form::label('pavadinimas', 'Pavadinimas') !!}
            {!! Form::text('pavadinimas', $zanras->pavadinimas, array('class' => 'form-control')) !!}
        </div>
        {!! Form::submit('Pridėti', array('class' => 'btn btn-primary')) !!} 
    {{ Form::close() }}
  </div>
</div>
@endsection

resources/views/zanrai/index.blade.php
@extends('layout.main')
 
@section('content')
    <h1>Žanrai</h1>
    @if(count($zanrai) > 0)
        @foreach($zanrai as $zanras)
            <div class="well">
                <h3><a href="/filmai/public/zanrai/{{$zanras->id}}">{{$zanras->pavadinimas}}</a></h3>
            </div>
        @endforeach
        {{$zanrai->links()}}
    @else
        <p>Nera jokiu žanrų</p>
    @endif
    <a class='btn btn-primary' href="{{ route('zanrai.create') }}">Pridėti žanrą</a>
@endsection

resources/views/zanrai/show.blade.php
@extends('layout.main')
 
@section('content')
    <h1>{{$zanras->vardas}} {{$zanras->pavarde}}</h1>
    <a href="{{ route('zanrai.edit', $zanras->id)}}" class="btn btn-sm btn-primary">Redaguoti</a>
    <form action="{{ route('zanrai.destroy', $zanras->id)}}" method="post">
        @csrf
        @method('DELETE')
        <button class="btn btn-danger btn-sm" type="submit">Trinti</button>
    </form>
@endsection