routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "FilmaiController@index");
Route::get('/about', "FilmaiController@about");
Route::get('/contact', "FilmaiController@contact");
Route::get('/movies', "FilmaiController@movies");

Auth::routes();

Route::resource('aktoriai', 'AktoriaiController');
Route::resource('rezisieriai', 'RezisieriaiController');
Route::resource('zanrai', 'ZanraiController');
Route::resource('paveiksleliai', 'PaveiksleliaiController');

Route::get('/home', 'HomeController@index')->name('home');
/*
|--------------------------------------------------------------------------
| These routes were added by jamesmills/laravel-admin page
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'roles'], 'roles' => 'admin'], function () {
    Route::get('/', 'Admin\AdminController@index')->name('dashboard');
    Route::resource('roles', '\JamesMills\LaravelAdmin\Controllers\Admin\RolesController');
    Route::resource('permissions', '\JamesMills\LaravelAdmin\Controllers\Admin\PermissionsController');
    Route::resource('users', '\JamesMills\LaravelAdmin\Controllers\Admin\UsersController');
});

resources/views/admin/dashboard.blade.php
@extends('layouts.backend')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        Your application's dashboard.
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/sidebar.blade.php
<div class="col-md-3">

    <div class="card">
        <div class="card-header">
            Backend
        </div>
        <div class="card-body">
            <ul class="nav flex-column" role="tablist">
                <li class="nav-item" role="presentation">
                    <a href="{{ route('admin.dashboard') }}">Admin Dashboard</a>
                </li>
            </ul>
        </div>
    </div>

    <br/>

    <div class="card">
        <div class="card-header">
            Users / Roles / Permissions
        </div>
        <div class="card-body">
            <ul class="nav flex-column" role="tablist">
                <li class="nav-item" role="presentation">
                    <a href="{{ route('admin.users.index') }}">All users</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a href="{{ route('admin.users.create') }}">Create user</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a href="{{ route('admin.roles.index') }}">All roles</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a href="{{ route('admin.roles.create') }}">Create role</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a href="{{ route('admin.permissions.index') }}">All permissions</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a href="{{ route('admin.permissions.create') }}">Create permission</a>
                </li>
            </ul>
        </div>
    </div>

</div>