routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "FilmaiController@index");
Route::get('/about', "FilmaiController@about");
Route::get('/contact', "FilmaiController@contact");
Route::get('/movies', "FilmaiController@movies");

Auth::routes();

Route::resource('aktoriai', 'AktoriaiController');
Route::resource('rezisieriai', 'RezisieriaiController');
Route::resource('zanrai', 'ZanraiController');
Route::resource('paveiksleliai', 'PaveiksleliaiController');

Route::get('/home', 'HomeController@index')->name('home');
/*
|--------------------------------------------------------------------------
| These routes were added by jamesmills/laravel-admin page
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'roles'], 'roles' => 'admin'], function () {
    Route::get('/', 'Admin\AdminController@index')->name('dashboard');
    Route::resource('roles', '\JamesMills\LaravelAdmin\Controllers\Admin\RolesController');
    Route::resource('permissions', '\JamesMills\LaravelAdmin\Controllers\Admin\PermissionsController');
    Route::resource('users', '\JamesMills\LaravelAdmin\Controllers\Admin\UsersController');
});

resources/views/images/create.blade.php
@extends('layout.main')
 
@section('content')
    <h1>Įkelti paveikslėlį</h1>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    {!! Form::open(array('route' => 'paveiksleliai.store', 'files'=>true)) !!}
        {!! Form::token() !!}
        <div class="form-group">
            {!! Form::label('pavadinimas', 'Pavadinimas') !!}
            {!! Form::text('pavadinimas', ' ', array('class' => 'form-control')) !!}
        </div>
        <div class="form-group">
            {!! Form::label('kelias', 'Įkelti paveikslėlį') !!}
            {!! Form::file('kelias', array('class' => 'form-control')) !!}
        </div>
        {!! Form::submit('Pridėti', array('class' => 'btn btn-primary')) !!} 
    {!! Form::close() !!}
@endsection

resources/views/images/edit.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Redaguoti darbą
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    {!! Form::open(array('route' => array('aktoriai.update', $aktorius->id))) !!}
        @method('PATCH')
        {!! Form::token() !!}
        {!! Form::hidden('id', $aktorius->id) !!}
        <div class="form-group">
            {!! Form::label('vardas', 'Vardas') !!}
            {!! Form::text('vardas', $aktorius->vardas, array('class' => 'form-control')) !!}
        </div>
        <div class="form-group">
            {!! Form::label('pavarde', 'Pavardė') !!}
            {!! Form::text('pavarde', $aktorius->pavarde, array('class' => 'form-control')) !!}
        </div>
        {!! Form::submit('Pridėti', array('class' => 'btn btn-primary')) !!} 
    {{ Form::close() }}
  </div>
</div>
@endsection

resources/views/images/index.blade.php
@extends('layout.main')
 
@section('content')
    <h1>Paveikslėliai</h1>
    @if(count($images) > 0)
        @foreach($images as $image)
            <div class="well">
                <h3><a href="/filmai/public/paveiksleliai/{{$image->id}}">{{$image->pavadinimas}}</a></h3>
                <div><img src="{{ asset('images/') }}/{{$image->kelias}}" alt="{{$image->pavadinimas}}"></div>
            </div>
        @endforeach
        {{$images->links()}}
    @else
        <p>Nėra jokiu paveikslėlių</p>
    @endif
    <a class='btn btn-primary' href="{{ route('paveiksleliai.create') }}">Įkelti paveikslėlį</a>
@endsection

resources/views/images/show.blade.php
@extends('layout.main')
 
@section('content')
<h3><a href="/filmai/public/paveiksleliai/{{$image->id}}">{{$image->pavadinimas}}</a></h3>
<div><img src="{{ asset('images/') }}/{{$image->kelias}}" alt="{{$image->pavadinimas}}"></div>
    <a href="{{ route('paveiksleliai.edit', $image->id)}}" class="btn btn-sm btn-primary">Redaguoti</a>
    <form action="{{ route('paveiksleliai.destroy', $image->id)}}" method="post">
        @csrf
        @method('DELETE')
        <button class="btn btn-danger btn-sm" type="submit">Trinti</button>
    </form>
@endsection